- name: Purge CDN cache
  run: |
    curl -X POST "https://api.cloudflare.com/client/v4/zones/YOUR_ZONE_ID/purge_cache" \
    -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
    -H "Content-Type: application/json" \
    --data '{"purge_everything":true}'
